# Generated by Django 5.1.1 on 2024-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
