# Generated by Django 5.1 on 2024-09-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
