# Generated by Django 3.2.25 on 2024-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="images/24/9/12/profile.png", upload_to="images/%y/%m/%d"
            ),
        ),
    ]
