# Generated by Django 4.2.13 on 2024-09-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_image"),
        ("account", "0009_alter_user_image"),
    ]

    operations = []
