# Generated by Django 4.2.13 on 2024-09-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_is_admin"),
        ("account", "0010_merge_0004_user_image_0009_alter_user_image"),
    ]

    operations = []
