# Generated by Django 5.1.1 on 2024-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
