# Generated by Django 4.2.13 on 2024-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_image_post_likes_alter_post_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
