# Generated by Django 4.2.13 on 2024-09-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_post_author_name_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default=0, upload_to=""),
        ),
    ]
