# Generated by Django 4.2.13 on 2024-09-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_post_image"),
        ("post", "0006_post_author_image_post_comment"),
    ]

    operations = []
