# Generated by Django 4.2.13 on 2024-09-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_merge_20240923_0016"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
