# Generated by Django 5.1.1 on 2024-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('performer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('number_of_tickets', models.IntegerField()),
            ],
        ),
    ]
