# Generated by Django 4.2.13 on 2024-09-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0003_party_descripition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="party",
            old_name="descripition",
            new_name="description",
        ),
    ]
