# Generated by Django 3.2.25 on 2024-09-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_party_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='image',
            field=models.ImageField(default='images/24/9/12/profile.png', upload_to='images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='party_user',
            name='card_cvv',
            field=models.CharField(max_length=3),
        ),
    ]
