# Generated by Django 3.2.25 on 2024-09-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_auto_20240927_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_user',
            name='month',
            field=models.CharField(default=12, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party_user',
            name='year',
            field=models.CharField(default=23, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(default='images/24/9/12/party.jpeg', upload_to='images/%y/%m/%d'),
        ),
    ]
