# Generated by Django 5.1.1 on 2024-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0003_alter_match_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="no_tickets",
            field=models.IntegerField(default=0),
        ),
    ]
