# Generated by Django 5.1.1 on 2024-09-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0004_match_no_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
