# Generated by Django 5.1.1 on 2024-09-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0005_match_ticket_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="avilable",
            field=models.BooleanField(default=False),
        ),
    ]
