# Generated by Django 5.1.1 on 2024-09-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0006_match_avilable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="avilable",
            field=models.BooleanField(default=True),
        ),
    ]
