# Generated by Django 5.1.1 on 2024-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0007_alter_match_avilable"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="matches/%y/%m/%d"
            ),
        ),
    ]
