# Generated by Django 5.1.1 on 2024-09-17 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match", "0005_match_ticket_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="match_reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets_reserved", models.IntegerField()),
                ("match_id", models.ManyToManyField(to="match.match")),
                ("user_id", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
