# Generated by Django 5.1.1 on 2024-09-28 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match", "0008_match_image_alter_match_date_alter_match_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="match_reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets_reserved", models.IntegerField()),
                (
                    "date_of_reservation",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "pay_method",
                    models.CharField(
                        choices=[("offline", "cash"), ("online", "visa_card")],
                        default="offline",
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "match_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="match.match"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="online_match_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visa_card", models.CharField(max_length=16)),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Pending"), ("c", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "reservation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.match_reservation",
                    ),
                ),
            ],
        ),
    ]
