# Generated by Django 5.1.1 on 2024-09-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="match_reservation",
        ),
    ]
