# Generated by Django 5.1.1 on 2024-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match_reservation",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[("P", "Pending"), ("c", "Complete"), ("F", "Failed")],
                default="P",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match_reservation",
            name="visa_card",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
