# Generated by Django 5.1.1 on 2024-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_match_reservation_payment_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match_reservation",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="match_reservation",
            name="visa_card",
        ),
        migrations.AddField(
            model_name="match_reservation",
            name="pay_method",
            field=models.CharField(
                choices=[("offline", "Cash"), ("online", "visa_card")],
                default="Cash",
                max_length=30,
            ),
        ),
    ]
