# Generated by Django 5.1.1 on 2024-09-23 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0007_alter_match_avilable"),
        ("reservation", "0005_remove_match_reservation_payment_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="online_match_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visa_card", models.IntegerField()),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Pending"), ("c", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "match_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="match.match"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
