# Generated by Django 5.1.1 on 2024-09-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0006_online_match_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="online_match_payment",
            name="match_id",
        ),
        migrations.RemoveField(
            model_name="online_match_payment",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="online_match_payment",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="online_match_payment",
            name="visa_card",
        ),
    ]
