# Generated by Django 5.1.1 on 2024-09-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_remove_online_match_payment_match_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="online_match_payment",
        ),
    ]
