# Generated by Django 5.1.1 on 2024-09-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_delete_online_match_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="online_match_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visa_card", models.IntegerField()),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Pending"), ("c", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "reservation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.match_reservation",
                    ),
                ),
            ],
        ),
    ]
