# Generated by Django 5.1.1 on 2024-09-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0009_online_match_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_match_payment",
            name="visa_card",
            field=models.CharField(max_length=19),
        ),
    ]
