# Generated by Django 5.1.1 on 2024-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0011_alter_online_match_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_match_payment",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[("P", "Pending"), ("c", "Complete"), ("F", "Failed")],
                default="P",
                max_length=1,
                null=True,
            ),
        ),
    ]
