# Generated by Django 5.1.1 on 2024-09-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0012_alter_online_match_payment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_match_payment",
            name="reservation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.match_reservation",
                unique=True,
            ),
        ),
    ]
