# Generated by Django 5.1.1 on 2024-09-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0013_alter_online_match_payment_reservation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="online_match_payment",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="online_match_payment",
            name="reservation_id",
        ),
        migrations.RemoveField(
            model_name="online_match_payment",
            name="visa_card",
        ),
    ]
