# Generated by Django 5.1.1 on 2024-09-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0014_remove_online_match_payment_payment_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="online_match_payment",
        ),
    ]
